print ( "Cześć jestem Python i  miło mi cie poznać !")
print ( "Jak masz na imię" )
imie =input()
print (imie) 
print ("Hej " ,imie , " czy chcesz iśc na grzyby" ) 
print (" w co lubisz grać ") 
gra=input ()
imie = 'Harold'
print ( " o ja tez lubie grać w " ,gra ) 
print (" Jaki smak lodów lubisz najbardziej")
smak=input ()
print (" no myśle żę  ", smak ,"to bardzo dobry wybór  też je lubie") 
print ("co wolisz koty czy psy" )
zwierze=input ()
print ("Też tak myśle "  ,zwierze, " są takie słodkie")
rok=input("W którym roku sie urodziłeś?")
wiek = 2024 - int(rok)
print (" O czyli masz", "", wiek," lat! ")
godzina=input( "O której wstajesz do szkoły")
aktualna = 20 - int(godzina) # tu była zmienna "aktualna"